### ISSUE TITLE
About the model used to test the entire network

### ISSUE THREAD

**Issue by genius9527** [LiMeng95/MultiPoseNet.pytorch#10]
Thank you very much for your answer.If I want to use multipose_coco_eval.py to evaluate the performance of the entire network, which model should be loaded. Is it the last model trained by multipose_prn_train.py?

**Comment by LiMeng95** [comment]
@genius9527 hi,
Yes, we trained the final model using 'multipose_prn_train.py'. And the checkpoint file used in 'multipose_prn_train.py' is from 'multipose_detection_train.py'

**Comment by genius9527** [comment]
ok.is the checkpoint file used in 'multipose_detection_train.py' is from 'multipose_keypoint_train.py‘？

**Comment by genius9527** [comment]
OK.Is the checkpoint file used in 'multipose_detection_train.py' is from 'multipose_keypoint_train.py‘？

**Comment by LiMeng95** [comment]
@genius9527 ，
Yes, you're right

> OK.Is the checkpoint file used in 'multipose_detection_train.py' is from 'multipose_keypoint_train.py‘？
