### ISSUE TITLE
目前项目的表现是在validation数据集上的还是test-dev上的？

### ISSUE THREAD

**Issue by hellojialee** [LiMeng95/MultiPoseNet.pytorch#12]
您好，感谢分享！请问README中的AP指标是在哪个子数据集上的结果？

**Comment by LiMeng95** [comment]
现在mAP是在val2017上的结果。目前结果还比论文中的结果差一些，有待改进

**Comment by hellojialee** [comment]
谢谢！复现出表现不错的project已经非常不容易了，点赞。
Waiting for your improved version!
