### ISSUE TITLE
Inference time and running on CPU

### ISSUE THREAD

**Issue by karimamd** [LiMeng95/MultiPoseNet.pytorch#13]
Hello,
You have made a great implementation.
I have 2 questions please
how much frame rate did you produce for a video 
and can this model be tested on a CPU with no GPUs ?

**Comment by LiMeng95** [comment]
@karimamd 
Thanks for your question.

1. With one GTX1080Ti, the version [686b9a4](https://github.com/LiMeng95/MultiPoseNet.pytorch/commit/686b9a488b221df90430c085dc056619087417ff) can run at 10 fps. We are trying to upgrade the code to increase the frame rate.

2. Yes, this model can be tested without a GPU, but version [686b9a4](https://github.com/LiMeng95/MultiPoseNet.pytorch/commit/686b9a488b221df90430c085dc056619087417ff) don't support CPU-only mode now. If your want, you can try deleting the '.cuda()' on Line 127/212/291/403 in the [tester.py](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/evaluate/tester.py) file.
