### ISSUE TITLE
I want to know the best result of this work?

### ISSUE THREAD

**Issue by do-oo** [LiMeng95/MultiPoseNet.pytorch#14]
first, i will appreciate your  PRN'S Implement! 
so, i want to know your best MAP, how much?
how much the map about ablation experiment (dectection groundtruth + keypoints prediction) ?

**Comment by LiMeng95** [comment]
For now, the best mAP I can implement on val2017 is 0.590. In paper, the mAP is 0.639 (dectection prediction + keypoints prediction and no dilated).
I think maybe there is something wrong in my 'keypoint_subnet' code, and I am trying to improve it.

**Comment by LEESEYUN** [comment]
Could you tell me the reason that  the papers mAP is 0.639 ? 
In papers, they told that the best mAP is 0.69.6

Thank you!

**Comment by FoolishMao** [comment]
@LEESEYUN In paper, they tested with some tricks, so got 0.696.

**Comment by LiMeng95** [comment]
In paper, the best mAP on COCO test-dev is 0.696, on COCO val2017 is 0.639 (dectection prediction + keypoints prediction and no dilated)
