### ISSUE TITLE
Questions about training and evaluate

### ISSUE THREAD

**Issue by IgorMunizS** [LiMeng95/MultiPoseNet.pytorch#17]
Hi,

I am trying to replicate this work in Keras, but I haven't been able to achieve the same results. I started my implementation by following the article and based coco evaluation in your code. This achieve mAP 0.390.
 
Could you describe your training strategy and results at each stage?

Thanks!

**Comment by LiMeng95** [comment]
For training strategies, you can refer to [this issue](https://github.com/LiMeng95/MultiPoseNet.pytorch/issues/8#issuecomment-434647915).
