### ISSUE TITLE
Improvements detail

### ISSUE THREAD

**Issue by IgorMunizS** [LiMeng95/MultiPoseNet.pytorch#18]
Hi,

Could you please tell which was the main changing that improved your score from 0.39 to 0.59?

I'm trying to replicate this paper in keras and i'm stuck at 0.37 mAP.

Thanks.

**Comment by LiMeng95** [comment]
Hi,

The main changing is computing the keypoint heatmap of input image at different scales. I use the function [_get_multiplier](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/evaluate/tester.py#L256) return the computed scales.

**Comment by IgorMunizS** [comment]
Thanks for reply.
I'm already doing this, but i was not training Keypoint Net with intermediate supervision.
Hope this help.
