### ISSUE TITLE
this the numpy==1.14.3 and pycocotools==2.0.0 is ok? i have this error!

### ISSUE THREAD

**Issue by oujieww** [LiMeng95/MultiPoseNet.pytorch#19]
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

anyone can help me ? thank u for your answer~~~ ^_^

**Comment by LiMeng95** [comment]
@oujieww ,

All of my dependencies are in the `multipose_environment.yaml`. In my conda environment, pycocotools=2.0.0, numpy=1.14.3 is ok.

**Comment by joaqo** [comment]
@LiMeng95 I am getting the same error, and I am using the multipose_environment.yaml file correctly

**Comment by joaqo** [comment]
Fixed it by install pycocotools using: 

```bash
pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
``` 

instead of the instructions on the readme
