### ISSUE TITLE
multipose_environment.yaml file

### ISSUE THREAD

**Issue by sammiller06** [LiMeng95/MultiPoseNet.pytorch#20]
First off: thanks for the excellent documentation of this repo. By far the clearest pytorch implementation we've found yet!

The .yaml file for setting up a conda environment seems to be out of date. There are two main issues:

1) The Tsinghua conda channels no longer exist.
2) Given the above, the imports of pytorch, torchvision and cuda (first 3 packages) no longer work.

If helpful, I could push a solution?

Thanks,
Sam

**Comment by LiMeng95** [comment]
Thanks for your issues, I have deleted Tsinghua conda channels in `multipose_environment.yaml`. You can specify your own conda channel in `channels:` or use `defaults`.

And we will soon release a docker image for this repository.

**Comment by sammiller06** [comment]
Thanks! I have 1 more question but it's not a bug so will send you a message privately.

**Comment by joaqo** [comment]
@sammiller06 @LiMeng95 I am having this exact issue, can't install pytorch, torchvision and cuda with conda. How can I fix this? I am a beginner with anaconda.

**Comment by joaqo** [comment]
Nevermind, fixed it adding the pytorch channel to the channels in multipose_environment.yaml. Having other issues though, which I reported in a separate issue though.
