### ISSUE TITLE
PRN when using tester

### ISSUE THREAD

**Issue by abster95** [LiMeng95/MultiPoseNet.pytorch#22]
Hi,

I see in `/evaluate/multipose_coco_eval.py` that you're not using the `PRN` part of the network, and that there's a `prn_process` function that's not learned but heuristic.

Is there a way to actually evaluate the output of the PRN part of the network on mscoco dataset?

**Comment by LiMeng95** [comment]
hi,

In 'multipose_coco_eval.py', we get the keypoint heatmaps and bboxes in [L293](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/evaluate/tester.py#L293). And in `prn_process` function ([L404](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/evaluate/tester.py#L404)), we use the learned `PRN` part.

If you want to actually evaluate the pure PRN part, you can refer to [pose-residual-network-pytorch](https://github.com/salihkaragoz/pose-residual-network-pytorch)

**Comment by abster95** [comment]
Oh awesome! I missed that line when I looked at the function. Thanks for clearing that up.
