### ISSUE TITLE
Question about the baseline model

### ISSUE THREAD

**Issue by BananaLv26** [LiMeng95/MultiPoseNet.pytorch#23]
I have downloaded the baseline parameter ckpt file and it seems that the keypoint detection network did not use this when training while the person detection network and prn network both used it in your code. I feel confused about this.  What is the training process to get the baseline model parameters?
One more question, is it  appropriate if I use the baseline res101 ckpt as the detection network ckpt  instead of using the check point obtained after the keypoint traning?

**Comment by LiMeng95** [comment]
1. About training strategies, you can refer to [this issue](https://github.com/LiMeng95/MultiPoseNet.pytorch/issues/8#issuecomment-434647915). The `ckpt_baseline_resnet101.h5` file in download link is for evaluation purposes only and not for the training process.

2. I think you'd better use the ckpt file obtained from keypoint training. Because we don't update the backbone weights when training detection network. See [multipose_detection_train.py#L63](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/7b548fc20ae5b0141a2113669e8606103fb7e6d4/training/multipose_detection_train.py#L63)

**Comment by BananaLv26** [comment]
Thanks to your answer and really appreciate your work here.

**Comment by BananaLv26** [comment]
By the way, how many  epoches you used to train the baseline ckpt file in the keypoint network?

**Comment by LiMeng95** [comment]
It takes about 50 epochs to train keypoint network.

**Comment by BananaLv26** [comment]
> It takes about 50 epochs to train keypoint network.

When I ran the baseline model to test the images in demo file, I found the detection results differ a lot from the output image shown on README, since fewer people were detected and there were several boxes overlapping around the same person. Is this because of using the baseline or requiring other parameter settings？If the problem lies on using the baseline model, how many epoches did you use to train to achieve the final results?

**Comment by LiMeng95** [comment]
Did you use the model from my download link? If you are using my baseline model, you don't need any other parameter settings.

I forgot the exactly number of training epochs, you can reference to the `params.max_epoch` in `training/multipose_*_train.py`.

**Comment by BananaLv26** [comment]
> Did you use the model from my download link? If you are using my baseline model, you don't need any other parameter settings.
> 
> I forgot the exactly number of training epochs, you can reference to the `params.max_epoch` in `training/multipose_*_train.py`.

The output looks similar with  #7 ,and I used the model downloaded from the link in README.

**Comment by LiMeng95** [comment]
I cloned this project and tested the images in demo file with my baseline model without any changes, just run `python ./evaluate/multipose_test.py`. I found the output images is the same as images in README. I don't know what caused the difference between your results and mine. Please checkout whether your python environment is the same as my setting in [multipose_environment.yaml](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/multipose_environment.yaml)

**Comment by njustczr** [comment]
> I cloned this project and tested the images in demo file with my baseline model without any changes, just run `python ./evaluate/multipose_test.py`. I found the output images is the same as images in README. I don't know what caused the difference between your results and mine. Please checkout whether your python environment is the same as my setting in [multipose_environment.yaml](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/multipose_environment.yaml)

hello, multipose_test.py里面  segment_map = heatmaps[:, :, 17]  似乎不能得到分割用的mask啊

**Comment by LiMeng95** [comment]
@njustczr ,

你好，目前还没有加入分割相关内容。因此与segment_map相关的两行也都注释掉了。实际上是可以通过修改keypoint subnet部分的代码实现的。

**Comment by accountcwd** [comment]
> 
> 
> @njustczr ,
> 
> 你好，目前还没有加入分割相关内容。因此与segment_map相关的两行也都注释掉了。实际上是可以通过修改keypoint subnet部分的代码实现的。

你好，我一直有关注你的工程，请问以后还会有更多的改进吗？还是说之后的工作不方便公开了？

**Comment by LiMeng95** [comment]
@accountcwd ，

你好，之后会有改进的版本。不过最近在忙于秋招找工作，所以没有太多时间更新。等忙完这一阵应该会继续做一些修改的。也欢迎提PR。

**Comment by accountcwd** [comment]
好的，我最近也在重新跑一遍你的工程，有什么想法我们可以交流一下。

另，祝你找到理想的工作~！

**Comment by BananaLv26** [comment]
> @accountcwd ，
> 
> 你好，之后会有改进的版本。不过最近在忙于秋招找工作，所以没有太多时间更新。等忙完这一阵应该会继续做一些修改的。也欢迎提PR。


大神，实在是不好意思一直打扰你问问题(ORZ~~ )，因为我没有装annoconda,所以yaml里没有全部配齐，可能demo测试的问题是因为这个，我再重新装annoconda试一下。我还想知道（1）可以从keypoint network开始，在您之前提供的baseline上继续训练吗？2）*_eval.py中似乎是只有验证集上的损失，如果想知道Map的情况是需要自己另外计算的吗？祝秋招顺利！！

**Comment by LiMeng95** [comment]
@youning0701 ，

你好，过奖了。环境方面可能还是用conda比较好，等忙过这一阵我可能会发布一个docker。另外：
1. 可以在baseline上继续训练，但可能需要修改lr等参数，因为在已经训练好的模型上再用一个大一点的lr不太合适。另外我估计如果不换数据集的话，继续训练带来的提升会比较小。
2. *_eval.py中目前是只测试了val数据集的。如果要在test数据集上测试的话，需要修改一下[coco_eval](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/evaluate/tester.py#L131)函数中数据读取部分的结果，并注释掉最后evaluate相关部分。

**Comment by BananaLv26** [comment]
> @youning0701 ，
> 
> 你好，过奖了。环境方面可能还是用conda比较好，等忙过这一阵我可能会发布一个docker。另外：
> 
> 1. 可以在baseline上继续训练，但可能需要修改lr等参数，因为在已经训练好的模型上再用一个大一点的lr不太合适。另外我估计如果不换数据集的话，继续训练带来的提升会比较小。
> 2. *_eval.py中目前是只测试了val数据集的。如果要在test数据集上测试的话，需要修改一下[coco_eval](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/evaluate/tester.py#L131)函数中数据读取部分的结果，并注释掉最后evaluate相关部分。

好的~感谢！！你是用的coco 2017test-dev在线评估的Map结果吗

**Comment by LiMeng95** [comment]
你好，我现在测试是在coco_2017_val上做的。因为test-dev数据集没有groundtruth，需要上传结果才能得到MAP。如果想在test数据集上测试的话，就需要按照我说的第二点部分稍微修改一下代码。

**Comment by accountcwd** [comment]
> 
> 
> I cloned this project and tested the images in demo file with my baseline model without any changes, just run `python ./evaluate/multipose_test.py`. I found the output images is the same as images in README. I don't know what caused the difference between your results and mine. Please checkout whether your python environment is the same as my setting in [multipose_environment.yaml](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/multipose_environment.yaml)

你好，我下载你在清华云上的baselinemodel，输出的图片的确跟你readme上的不符， 就像#7 一样，而且有点像你在Oct 3, 2018  的commit上的图，请检查一下是否放错了model？

**Comment by LiMeng95** [comment]
您好，我前几天已经做过测试，也是直接用的清华云上的baseline模型。在我的环境里输出图片和readme里确实是相同的。并且在中 [#7](https://github.com/LiMeng95/MultiPoseNet.pytorch/issues/7) 提出的80类分类问题，目前已经改成了二分类:[posenet.py#L192](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/network/posenet.py#L192)。

我之后会再完整测试一下我的代码。如果发现确实是工程的问题，我会及时修正的。感谢你的提问！

希望目前的代码不会影响你后续使用。

**Comment by accountcwd** [comment]
> 
> 
> 您好，我前几天已经做过测试，也是直接用的清华云上的baseline模型。在我的环境里输出图片和readme里确实是相同的。并且在中 [#7](https://github.com/LiMeng95/MultiPoseNet.pytorch/issues/7) 提出的80类分类问题，目前已经改成了二分类:[posenet.py#L192](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/network/posenet.py#L192)。
> 
> 我之后会再完整测试一下我的代码。如果发现确实是工程的问题，我会及时修正的。感谢你的提问！
> 
> 希望目前的代码不会影响你后续使用。

谢谢~我暂时在训练keypoint subnet，遇到一些问题可能稍后会私信打扰你一下
