### ISSUE TITLE
ImportError: lib/nms/_ext/nms/_nms.so: undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by LouisNUST** [LiMeng95/MultiPoseNet.pytorch#24]
Traceback (most recent call last):
  File "./training/multipose_prn_train.py", line 12, in <module>
    from network.posenet import poseNet
  File "/home/louis/Documents/DetPose/MultiPoseNet/network/posenet.py", line 16, in <module>
    from lib.nms.pth_nms import pth_nms
  File "/home/louis/Documents/DetPose/MultiPoseNet/lib/nms/pth_nms.py", line 2, in <module>
    from ._ext import nms
  File "/home/louis/Documents/DetPose/MultiPoseNet/lib/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /home/louis/Documents/DetPose/MultiPoseNet/lib/nms/_ext/nms/_nms.so: undefined symbol: __cudaPopCallConfiguration

conda envs:
Ubuntu: 18.04
python: 3.6.8
pytorch: 0.4.1 
cuda90: 1.0

**Comment by LiMeng95** [comment]
hi, @LouisNUST 

Have you build your own NMS extension? See: [prerequisites-NMS extension](https://github.com/LiMeng95/MultiPoseNet.pytorch#prerequisites). And please ensure using the same cuda version with pytorch.

**Comment by LouisNUST** [comment]
@LiMeng95 Thanks for your reply.
I have precompiled my own NMS extentions:

Compiling nms kernels by nvcc...
Including CUDA code.
/home/louis/Documents/DetPose/MultiPoseNet/lib/nms
generating /tmp/tmpp59_1z1x/_nms.c
setting the current directory to '/tmp/tmpp59_1z1x'
running build_ext
building '_nms' extension
creating home
creating home/louis
creating home/louis/Documents
creating home/louis/Documents/DetPose
creating home/louis/Documents/DetPose/MultiPoseNet
creating home/louis/Documents/DetPose/MultiPoseNet/lib
creating home/louis/Documents/DetPose/MultiPoseNet/lib/nms
creating home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src
gcc -pthread -B /home/louis/anaconda3/envs/MultiPose/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/louis/anaconda3/envs/MultiPose/include/python3.6m -c _nms.c -o ./_nms.o -std=c99
gcc -pthread -B /home/louis/anaconda3/envs/MultiPose/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/louis/anaconda3/envs/MultiPose/include/python3.6m -c /home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms.c -o ./home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms.o -std=c99
In file included from /home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/TH.h:4:0,
                 from /home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms.c:1:
/home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms.c: In function ‘cpu_nms’:
/home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms.c:7:42: warning: passing argument 1 of ‘THLongTensor_isContiguous’ from incompatible pointer type [-Wincompatible-pointer-types]
     THArgCheck(THLongTensor_isContiguous(boxes), 2, "boxes must be contiguous");
                                          ^
/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:100:35: note: in definition of macro ‘THArgCheck’
   _THArgCheck(__FILE__, __LINE__, __VA_ARGS__);                       \
                                   ^~~~~~~~~~~
/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:8:39: note: expected ‘const THLongTensor * {aka const struct THLongTensor *}’ but argument is of type ‘THFloatTensor * {aka struct THFloatTensor *}’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                                       ^
/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:144:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
 #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
                                     ^
/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:8:27: note: in expansion of macro ‘TH_CONCAT_4’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                           ^~~~~~~~~~~
/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:114:12: note: in expansion of macro ‘THTensor_’
 TH_API int THTensor_(isContiguous)(const THTensor *self);
            ^~~~~~~~~
/home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms.c:9:42: warning: passing argument 1 of ‘THLongTensor_isContiguous’ from incompatible pointer type [-Wincompatible-pointer-types]
     THArgCheck(THLongTensor_isContiguous(areas), 4, "areas must be contiguous");
                                          ^
/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:100:35: note: in definition of macro ‘THArgCheck’
   _THArgCheck(__FILE__, __LINE__, __VA_ARGS__);                       \
                                   ^~~~~~~~~~~
/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:8:39: note: expected ‘const THLongTensor * {aka const struct THLongTensor *}’ but argument is of type ‘THFloatTensor * {aka struct THFloatTensor *}’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                                       ^
/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:144:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
 #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
                                     ^
/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:8:27: note: in expansion of macro ‘TH_CONCAT_4’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                           ^~~~~~~~~~~
/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:114:12: note: in expansion of macro ‘THTensor_’
 TH_API int THTensor_(isContiguous)(const THTensor *self);
            ^~~~~~~~~
gcc -pthread -B /home/louis/anaconda3/envs/MultiPose/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/louis/anaconda3/envs/pytorch36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/louis/anaconda3/envs/MultiPose/include/python3.6m -c /home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms_cuda.c -o ./home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms_cuda.o -std=c99
/home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms_cuda.c: In function ‘gpu_nms’:
/home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms_cuda.c:29:35: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   unsigned long long* mask_flat = THCudaLongTensor_data(state, mask);
                                   ^~~~~~~~~~~~~~~~~~~~~
/home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms_cuda.c:37:40: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   unsigned long long * mask_cpu_flat = THLongTensor_data(mask_cpu);
                                        ^~~~~~~~~~~~~~~~~
/home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms_cuda.c:40:39: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   unsigned long long* remv_cpu_flat = THLongTensor_data(remv_cpu);
                                       ^~~~~~~~~~~~~~~~~
/home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms_cuda.c:23:7: warning: unused variable ‘boxes_dim’ [-Wunused-variable]
   int boxes_dim = THCudaTensor_size(state, boxes, 1);
       ^~~~~~~~~
gcc -pthread -shared -B /home/louis/anaconda3/envs/MultiPose/compiler_compat -L/home/louis/anaconda3/envs/MultiPose/lib -Wl,-rpath=/home/louis/anaconda3/envs/MultiPose/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_nms.o ./home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms.o ./home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/nms_cuda.o /home/louis/Documents/DetPose/MultiPoseNet/lib/nms/src/cuda/nms_kernel.cu.o -o ./_nms.so


the CUDA version is 10.1
Ubuntu: 18.04
python: 3.6.8
pytorch: 0.4.1
cuda90: 1.0

**Comment by LiMeng95** [comment]
@LouisNUST ,

Maybe the mismatch of CUDA version caused this problem. I used CUDA9.0, so that you can find package `cuda90: 1.0` in [multipose_environment.yaml](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/multipose_environment.yaml)
