### ISSUE TITLE
Build the NMS extension

### ISSUE THREAD

**Issue by accountcwd** [LiMeng95/MultiPoseNet.pytorch#25]
TypeError: dist must be a Distribution instance

**Comment by accountcwd** [comment]
```
bash build.sh
Compiling nms kernels by nvcc...
Compiling
Including CUDA code.
/workspace/MultiPoseNet.pytorch/lib/nms
Traceback (most recent call last):
  File "build.py", line 32, in <module>
    extra_compile_args=['-std=c99']
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 147, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib/python3.6/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
```


你好，我编译nms的时候报这样的错，请问有什么头绪吗？
ubuntu16.04.10
cuda10.0
pytorch0.4.1
python3.6.8

**Comment by LiMeng95** [comment]
你好，你可以查看一下是否是setuptools版本问题。我使用的版本是`setuptools=39.1.0=py36_0`

**Comment by accountcwd** [comment]
> 
> 
> 你好，你可以查看一下是否是setuptools版本问题。我使用的版本是`setuptools=39.1.0=py36_0`

感谢，网上好多人有这个问题，我已试过安装setuptools=39.1.0的版本，依然报错。
我现在用的GPU是Titan RTX，cuda只能用10.0版本， 也不支持pytorch0.4.0，不过这个编译问题应该跟这些没关系吧？我再研究一下

**Comment by LiMeng95** [comment]
好的，抱歉确实不太清楚是什么问题。期待你的解决方案

**Comment by accountcwd** [comment]
解决了，应该是我之前的pytorch版本是1.0，
遇到`ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.` 这个问题的时候把ffi的换了，最后发现1.0还是跑不了你的程序，退回0.4的时候忘记把这个改回来了。

顺便问一句，这工程你有更新到pytoch1.0以上的打算吗？

**Comment by LiMeng95** [comment]
嗯，有时间的话会更新的

**Comment by LouisChen0104** [comment]
Pytorch 1.0 可以参考这个https://github.com/yhenon/pytorch-retinanet/issues/66
