### ISSUE TITLE
No such file or directory: '/data/COCO/COCO.json'

### ISSUE THREAD

**Issue by LouisNUST** [LiMeng95/MultiPoseNet.pytorch#26]
Where can I find this file? COCO.json

${COCO_ROOT}
   --annotations
      --instances_train2017.json
      --instances_val2017.json
      --person_keypoints_train2017.json
      --person_keypoints_val2017.json
   --images
      --train2014
      --val2014
      --train2017
      --val2017
   --mask2014
   --COCO.json

**Comment by accountcwd** [comment]
you shuold follow this in readme 

> For Training Keypoint Estimation Subnet, we followed ZheC/Realtime_Multi-Person_Pose_Estimation's first 4 Training Steps prepared our COCO2014 dataset (train2014, val2014 and mask2014).
>     We also use COCO2017 dataset to train Person Detection Subnet.
