### ISSUE TITLE
COCO.json?

### ISSUE THREAD

**Issue by Minotaur-CN** [LiMeng95/MultiPoseNet.pytorch#3]
Can u upload coco.json ?
I can not find under coco dir.

Thanks!

**Comment by LiMeng95** [comment]
Hi, @Minotaur-CN ,
As we mentioned in [Data preparation](https://github.com/LiMeng95/MultiPoseNet.pytorch#data-preparation) section: we followed [ZheC/Realtime_Multi-Person_Pose_Estimation's first 4 Training Steps](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation#training-steps) prepared our COCO2014 dataset, including 'mask2014' and 'COCO.json'. You can run 'genJSON('COCO')' to generate 'COCO.json'.
