### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by zkloveai** [LiMeng95/MultiPoseNet.pytorch#4]
你好。请问可不可以在多人姿态中对某个人进行姿态测量。

**Comment by LiMeng95** [comment]
@zkloveai ， 你好，
请问您所说的“对某个人进行测量”指的是什么意思呢？现在的代码是可以得到每个被检测出的人的关键点数据的。[结果示例](https://github.com/LiMeng95/MultiPoseNet.pytorch/tree/master/demo/output)

**Comment by zkloveai** [comment]
我已经复现您的算法。我的意思是在多人环境下对某一个人的姿态测量。
我使用的是用opencv对视频进行提取图片放到你的网络中检测，我的图片的人物大部分是背向摄像头的，检测效果大部分只有部分关键点，没有线段的连接。
@LiMeng95

**Comment by LiMeng95** [comment]
@zkloveai ,你好，
正常情况下，背向摄像头的检测结果应该与[该图](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/demo/output/pic4_canvas.png)右侧人物检测结果类似。
请问您是在使用中遇到什么问题了么？是检测效果不好还是有其他问题？可能的话最好把您的检测结果通过链接发到这里。

**Comment by zkloveai** [comment]
对的。是那个效果。请问他处理单张图的时间是多少。还有resize的大小能改吗？（我看到你的代码是 480.）

**Comment by frotms** [comment]
您好，请教一下，原论文中能做到23fps，我在测试的时候只能达到10fps左右，用的是1080ti，请问这是什么原因呢？

**Comment by LiMeng95** [comment]
@zkloveai , 你好，
现在这个版本的代码能实现的fps是在15左右。resize的大小是可以修改，只要保证是32的倍数即可

**Comment by LiMeng95** [comment]
@frotms ，你好，
我测试coco_eval的时候fps在15左右，GPU也是1080ti。处理速度还有可能与CPU条件和输入图像大小有关。另外现在这个版本的代码还有待修改，可能也有代码不完善的原因。目前还在继续改进

**Comment by frotms** [comment]
@LiMeng95 好的，谢谢回答

**Comment by frotms** [comment]
期待优化的版本
